---
id: 363335a1ea
question: Error index 311297 is out of bounds for axis 0 with size 131483 when loading
  parquet file.
sort_order: 10
---

Problem description: Running `starter.ipynb` in homeworkâ€™s Q1 will show this error.

Solution:

- Update pandas along with related dependencies to the latest versions.